# Generated by Django 5.2.14 on 2026-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0003_countrythreat'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
